### ISSUE TITLE
Temperature Readings About 2 X Too High

### ISSUE THREAD

**Issue by TSJim** [enjoyneering/MAX31855#2]
I'm using your unmodified "MAX31855_sw_SPI_Demo" sketch with a MAX31855 and a NodeMCU-32S (ESP32).  The only change I have made to the sketch is:

  MAX31855soft myMAX31855(5, 19, 23); //for ESP8266 use D3, D4, D7

I'm getting a temperature reading on both "getColdJunctionTemperature()" and "getTemperature()" of nearly 2x what it should be.

I have checked the thermocouple with a dedicated thermocouple measuring meter, and it is correctly showing the TC at room temperature (about 28 degrees C right now).  But with the same thermocouple and environment, the internal and external readings from your library are both giving me around 67 degrees C.

I have also swapped the Adafruit MAX31855 library into my sketch, and it also reports around 28 degrees from the same circuit, which is correct.

What could be causing a high-temperature reading of both the internal and external temperatures from your library?

**Comment by enjoyneering** [comment]
let me check

**Comment by bleckers** [comment]
I have the same issue with the software SPI.

I changed the readRawData function to the following and all seems fine now (clock is inverted and i = 31 rather than 32):

```
int32_t MAX31855soft::readRawData(void)
{
  int32_t rawData = 0;

  digitalWrite(_cs, LOW);                        //stop  measurement/conversion
  delayMicroseconds(1);                          //4MHz  is 0.25usec, do we need it???
  digitalWrite(_cs, HIGH);                       //start measurement/conversion
  delay(MAX31855_CONVERSION_TIME);

  digitalWrite(_cs, LOW);                        //set CS low to enable SPI interface for MAX31855
  digitalWrite(_sck, LOW);
  
  delayMicroseconds(1); 
  
  for (int8_t i = 31; i >= 0; i--)               //read 32-bits via software SPI, in order MSB->LSB (D31..D0 bit)
  {
    digitalWrite(_sck, LOW);
    rawData = (rawData << 1) | digitalRead(_so);
    digitalWrite(_sck, HIGH);
  } 

  digitalWrite(_cs, HIGH);                       //disables SPI interface for MAX31855, but it will initiate measurement/conversion

  return rawData;
}
```

**Comment by JonRobert** [comment]
Same issue but more information:
I'm using hardware SPI,  Arduino 1.8.10  STM32 (Blue Pill STM32 core 1.5.0)

When I run the Sensor on a Pro Mini (3.3v, 8Mhz) the sensor reads correctly (or as near as I can tell)
When I run the Sensor on a Blue Pill (3.3v, ??? Mhz) the sensor reads 20 degrees high (or 2X as room temp is ~ 20 °C)
When I run the Sensor on the same Blue Pill, but with the Adafruit library the sensor reads correctly.

John

**Comment by enjoyneering** [comment]
Hi, thank you for feed back.

bleckers, I added digitalWrite(_sck, LOW) and fixed 32 bit read.
JonRobert, TSJim, I moved digitalWrite(_cs, LOW); after SPI.beginTransaction, like JohnRob suggested [here](https://forum.arduino.cc/index.php?topic=648927). 

Can you run the code and check? Thank you.

**Comment by bleckers** [comment]
The changes work for me.

**Comment by enjoyneering** [comment]
bleckers, thank you for feedback.

I still don’t understand why this happened. At the end of begin() I set _sck to a low level, so it should be low at the beginning of readRawData(), and at the end of readRawData() I keep it low again. I think the problem was in the extra bit (i= 31, not 32)
