### ISSUE TITLE
Missing "virtual" declaration in MAX31855.h

### ISSUE THREAD

**Issue by Stego72** [enjoyneering/MAX31855#3]
Hi - Great work.

In order to get the Soft SPI version to work the "virtual" declaration of:

int32_t  readRawData(void); 

In MAX21855.h line 95 must be added to be:

virtual int32_t  readRawData(void);

Otherwise the bit bang method of the derived class (MAX31855soft) is not called from the parent class when reading data.

BR

Stego72

**Comment by enjoyneering** [comment]
Thank you.

You are right https://www.geeksforgeeks.org/virtual-function-cpp/

Didn't know about virtual.

Done. Please check.

**Comment by enjoyneering** [comment]
How about begin() in MAX21855.h? Should it be virtual too?

The reason I ask, I'm not a programmer, Arduino is my hobby. I do it for fun.

**Comment by Stego72** [comment]
One could add the virtual declaration to begin() as well (no harm). 

However, it is only strictly needed if begin() is called inside the base class or if a MAX31855soft object is being used via a MAX31855 pointer or reference
